services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    image: node:alpine
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Отображаем порт 5432 на хост-машину

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Отображаем порт 80 на хост-машину под номером 5050
    depends_on:
      - db

volumes:
  pgdata: {}
  pgadmin-data: {}